name: Labels2
on:
  push:
    branches:
    - 'main'
  pull_request:
    types: [opened, synchronize, reopened, labeled]
jobs:
  build:
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'run:pr' }}    
    name: Test label PR
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
        
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - run: python print.py
      
      - run: pip install nox

      - name: Run nox session
        run: nox --sessions test-${{ matrix.python-version }}
        env:
          TEST_VAR: ${{ secrets.TEST_VAR }}

  label:
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'run:pr' }}    
    name: Run test
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
        
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - run: python print.py
      
      - run: pip install nox

      - name: Run nox session
        run: nox --sessions test-${{ matrix.python-version }}
        env:
          TEST_VAR: ${{ secrets.TEST_VAR }}
